# Generated by Django 4.2.7 on 2023-11-10 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_auto', models.CharField(max_length=9, verbose_name='Номер автомобиля')),
                ('description', models.TextField(verbose_name='Описание нарушения')),
            ],
            options={
                'verbose_name': 'Нарушение',
                'verbose_name_plural': 'Нарушения',
            },
        ),
    ]
