# Generated by Django 4.2.7 on 2023-11-10 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('в рассмотреннии', 'в рассмотреннии'), ('отклонено', 'отклонено')], default='', max_length=100, verbose_name='Статус'),
        ),
    ]
